package main

import (
	"bufio"
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"strings"
)

var opcodeMap = map[string]string{
	"illegal":    "",
	"lui":        "LoadUpperImm",
	"auipc":      "AddUpperImmPC",
	"jal":        "JumpAndLink",
	"jalr":       "JumpAndLinkReg",
	"beq":        "BrEqual",
	"bne":        "BrNotEqual",
	"blt":        "BrLessThan",
	"bge":        "BrGreaterEqual",
	"bltu":       "BrLessThanUnsigned",
	"bgeu":       "BrGreaterEqualUnsigned",
	"lb":         "LoadI8",
	"lh":         "LoadI16",
	"lw":         "LoadI32",
	"lbu":        "LoadU8",
	"lhu":        "LoadU16",
	"sb":         "StoreI8",
	"sh":         "StoreI16",
	"sw":         "StoreI32",
	"addi":       "ADDImm",
	"slti":       "SetLessThanImm",
	"sltiu":      "SetLessThanImmUnsigned",
	"xori":       "XORImm",
	"ori":        "ORImm",
	"andi":       "ANDImm",
	"slli":       "ShiftLeftLogicalImm",
	"srli":       "ShiftRightLogicalImm",
	"srai":       "ShiftRightArithmeticImm",
	"add":        "add\t",
	"sub":        "sub\t",
	"sll":        "ShiftLeftLogical",
	"slt":        "SetLessThan",
	"sltu":       "SetLesThanUnsigned",
	"xor":        "xor\t",
	"srl":        "ShiftRightLogical",
	"sra":        "ShiftRightArithmetic",
	"or":         "or\t",
	"and":        "and\t",
	"fence":      "fence\t",
	"fence.i":    "fence.i\t",
	"lwu":        "LoadU32",
	"ld":         "LoadI64",
	"sd":         "StoreI64",
	"addiw":      "ADDImmI32",
	"slliw":      "ShiftLeftLogicalImmI32",
	"srliw":      "ShiftRightLogicalImmI32",
	"sraiw":      "ShiftRihtArithmeticImmI32",
	"addw":       "ADDI32",
	"subw":       "SUBI32",
	"sllw":       "ShiftLeftLogicalI32",
	"srlw":       "ShiftRightLogicalI32",
	"sraw":       "ShiftRightArithmeticI32",
	"ldu":        "LoadU64",
	"lq":         "Load12I8",
	"sq":         "StoreI128",
	"addid":      "ADDImmI64",
	"sllid":      "ShiftLeftLogicalImmI64",
	"srlid":      "ShiftRightLogicalImmI64",
	"sraid":      "SiftRightArithmeticImmI64",
	"addd":       "ADDI64",
	"subd":       "SUBI64",
	"slld":       "ShiftLeftLogicalI64",
	"srld":       "ShiftRightLogicalI64",
	"srad":       "ShiftRightArithmeticI64",
	"mul":        "mul\t",
	"mulh":       "MULI16",
	"mulhsu":     "MUL16bitSinedUnsigned",
	"mulhu":      "MULU16",
	"div":        "dif\t",
	"divu":       "DIVUnsigned",
	"rem":        "rem\t",
	"remu":       "REMUnsigned",
	"mulw":       "MULI32",
	"divw":       "DIVI32",
	"divuw":      "DIVUnsignedI32",
	"remw":       "REMI32",
	"remuw":      "REMUnsignedI32",
	"muld":       "MULI64",
	"divd":       "DIVI64",
	"divud":      "DIVUnsignedI64",
	"remd":       "REMI64",
	"remud":      "REMUnsignedI64",
	"lr.w":       "LoadReservedI32",
	"sc.w":       "StoreConditionalI32",
	"amoswap.w":  "AtomicMemoryOperationSWAPI32",
	"amoadd.w":   "AtomicMemoryOperationADDI32",
	"amoxor.w":   "AtomicMemoryOperationXORI32",
	"amoor.w":    "AtomicMemoryOperationORI32",
	"amoand.w":   "AtomicMemoryOperationANDI32",
	"amomin.w":   "AtomicMemoryOperationMINI32",
	"amomax.w":   "AtomicMemoryOperationMAXI32",
	"amominu.w":  "AtomicMemoryOperationMINU32",
	"amomaxu.w":  "AtomicMemoryOperationMAXU32",
	"lr.d":       "LoadReservedI64",
	"sc.d":       "StoreConditionalI64",
	"amoswap.d":  "AtomicMemoryOperationSWAPI64",
	"amoadd.d":   "AtomicMemoryOperationADDI64",
	"amoxor.d":   "AtomicMemoryOperationXORI64",
	"amoor.d":    "AtomicMemoryOperationORI64",
	"amoand.d":   "AtomicMemoryOperationANDI64",
	"amomin.d":   "AtomicMemoryOperationMINI64",
	"amomax.d":   "AtomicMemoryOperationMAXI64",
	"amominu.d":  "AtomicMemoryOperationMINU64",
	"amomaxu.d":  "AtomicMemoryOperationMAXU64",
	"lr.q":       "LoadReservedI128",
	"sc.q":       "StoreConditionalI128",
	"amoswap.q":  "AtomicMemoryOperationSWAPI128",
	"amoadd.q":   "AtomicMemoryOperationADDI128",
	"amoxor.q":   "AtomicMemoryOperationXORI128",
	"amoor.q":    "AtomicMemoryOperationORI128",
	"amoand.q":   "AtomicMemoryOperationANDI128",
	"amomin.q":   "AtomicMemoryOperationMINI128",
	"amomax.q":   "AtomicMemoryOperationMAXI128",
	"amominu.q":  "AtomicMemoryOperationMINU128",
	"amomaxu.q":  "AtomicMemoryOperationMAXU128",
	"ecall":      "",
	"ebreak":     "",
	"uret":       "",
	"sret":       "",
	"hret":       "",
	"mret":       "",
	"dret":       "",
	"sfence.vm":  "",
	"sfence.vma": "",
	"wfi":        "",
	"csrrw":      "",
	"csrrs":      "",
	"csrrc":      "",
	"csrrwi":     "",
	"csrrsi":     "",
	"csrrci":     "",
	"flw":        "FloatLoadSingle",
	"fsw":        "FloatStoreSingle",
	"fmadd.s":    "FloatMulADD.Single",
	"fmsub.s":    "FloatMulSUB.Single",
	"fnmsub.s":   "FloatNegativeMulSUB.Single",
	"fnmadd.s":   "FloatNegativeMulADD.Single",
	"fadd.s":     "FloatADD.Single",
	"fsub.s":     "FloatSUB.Single",
	"fmul.s":     "FloatMUL.Single",
	"fdiv.s":     "FloatDIV.Single",
	"fsgnj.s":    "FloatSiGNinJection.Single",
	"fsgnjn.s":   "FloatSiGNinJectionNegative.Single",
	"fsgnjx.s":   "FloatSiGNinJectionXor.Single",
	"fmin.s":     "FloatMIN.Single",
	"fmax.s":     "FloatMAX.Single",
	"fsqrt.s":    "FloatSQRT.Single",
	"fle.s":      "FloatLessEqual.Single",
	"flt.s":      "FloatLessThan.Single",
	"feq.s":      "FloatEQual.Single",
	"fcvt.w.s":   "FloatConVerT.I32.Single",
	"fcvt.wu.s":  "FloatConVerT.U32.Single",
	"fcvt.s.w":   "FloatConVerT.Single.I32",
	"fcvt.s.wu":  "FloatConVerT.Single.U32",
	"fmv.x.s":    "FloatMV.toX.fromSingle",
	"fclass.s":   "FloatCLASSfiy.Single",
	"fmv.s.x":    "FloatMV.toSingle.fromX",
	"fcvt.l.s":   "FloatConVerT.I64.Single",
	"fcvt.lu.s":  "FloatConVerT.U64.Single",
	"fcvt.s.l":   "FloatConVerT.Single.I64",
	"fcvt.s.lu":  "FloatConVerT.Single.U64",
	"fld":        "FloatLoadDouble",
	"fsd":        "FloatStoreDouble",
	"fmadd.d":    "FloatMulADD.Double",
	"fmsub.d":    "FloatMulSUB.Double",
	"fnmsub.d":   "FloatNegativeMulSUB.Double",
	"fnmadd.d":   "FloatNegativeMulADD.Double",
	"fadd.d":     "FloatADD.Double",
	"fsub.d":     "FloatSUB.Double",
	"fmul.d":     "FloatMUL.Double",
	"fdiv.d":     "FloatDIV.Double",
	"fsgnj.d":    "FloatSiGNinJection.Double",
	"fsgnjn.d":   "FloatSiGNinJectionNegative.Double",
	"fsgnjx.d":   "FloatSiGNinJectionXor.Double",
	"fmin.d":     "FloatMIN.Double",
	"fmax.d":     "FloatMAX.Double",
	"fcvt.s.d":   "FloatConVerT.Single.Double",
	"fcvt.d.s":   "FloatConVerT.Double.Single",
	"fsqrt.d":    "FloatSQRT.Double",
	"fle.d":      "FloatLessEqual.Double",
	"flt.d":      "FloatLessThan.Double",
	"feq.d":      "FloatEQual.Double",
	"fcvt.w.d":   "FloatConVerT.I32.Double",
	"fcvt.wu.d":  "FloatConVert.U32.Double",
	"fcvt.d.w":   "FloatConVert.Double.I32",
	"fcvt.d.wu":  "FloatConVert.Double.U32",
	"fclass.d":   "FloatCLASSify.Double",
	"fcvt.l.d":   "FloatConVert.I64.Double",
	"fcvt.lu.d":  "FloatConVert.U64.Double",
	"fmv.x.d":    "FloatMoVe.x.Double",
	"fcvt.d.l":   "FloatConVert.Double.I64",
	"fcvt.d.lu":  "FloatConVert.Double.U64",
	"fmv.d.x":    "FloatMoVe.Double.x",
	"flq":        "FloatLoadQuad",
	"fsq":        "FloatStoreQuad",
	"fmadd.q":    "FloatMulADD.Quad",
	"fmsub.q":    "FloatMulSUB.Quad",
	"fnmsub.q":   "FloatNegativeMulSUB.Quad",
	"fnmadd.q":   "FloatNegativeMulADD.Quad",
	"fadd.q":     "FloatADD.Quad",
	"fsub.q":     "FloatSUB.Quad",
	"fmul.q":     "FloatMUL.Quad",
	"fdiv.q":     "FloatDIV.Quad",
	"fsgnj.q":    "FloatSiGNinJection.Quad",
	"fsgnjn.q":   "FloatSiGNinJectionNegative.Quad",
	"fsgnjx.q":   "FloatSiGNinJectionXor.Quad",
	"fmin.q":     "FloatMIN.Quad",
	"fmax.q":     "FloatMAX.Quad",
	"fcvt.s.q":   "FloatConVerT.Single.Quad",
	"fcvt.q.s":   "FloatConVerT.Quad.Single",
	"fcvt.d.q":   "FloatConVerT.Double.Quad",
	"fcvt.q.d":   "FloatConVerT.Quad.Double",
	"fsqrt.q":    "FloatSQRT.Quad",
	"fle.q":      "FloatLessEqual.Quad",
	"flt.q":      "FloatLessThan.Quad",
	"feq.q":      "FloatEQual.Quad",
	"fcvt.w.q":   "FloatConVerT.I32.Quad",
	"fcvt.wu.q":  "FloatConVerT.U32.Quad",
	"fcvt.q.w":   "FloatConVerT.Quad.I32",
	"fcvt.q.wu":  "FloatConVerT.Quad.U32",
	"fclass.q":   "FloatCLASSify.Quad",
	"fcvt.l.q":   "FloatConVerT.I64.Quad",
	"fcvt.lu.q":  "FloatConVerT.U64.Quad",
	"fcvt.q.l":   "FloatConVerT.Quad.I64",
	"fcvt.q.lu":  "FloatConVerT.Quad.U64",
	"fmv.x.q":    "FloatMoVe.x.Quad",
	"fmv.q.x":    "FloatMoVe.Quad.x",
	"c.addi4spn": "",
	"c.fld":      "",
	"c.lw":       "",
	"c.flw":      "",
	"c.fsd":      "",
	"c.sw":       "",
	"c.fsw":      "",
	"c.nop":      "",
	"c.addi":     "",
	"c.jal":      "",
	"c.li":       "",
	"c.addi16sp": "",
	"c.lui":      "",
	"c.srli":     "",
	"c.srai":     "",
	"c.andi":     "",
	"c.sub":      "",
	"c.xor":      "",
	"c.or":       "",
	"c.and":      "",
	"c.subw":     "",
	"c.addw":     "",
	"c.j":        "",
	"c.beqz":     "",
	"c.bnez":     "",
	"c.slli":     "",
	"c.fldsp":    "",
	"c.lwsp":     "",
	"c.flwsp":    "",
	"c.jr":       "",
	"c.mv":       "",
	"c.ebreak":   "",
	"c.jalr":     "",
	"c.add":      "",
	"c.fsdsp":    "",
	"c.swsp":     "",
	"c.fswsp":    "",
	"c.ld":       "",
	"c.sd":       "",
	"c.addiw":    "",
	"c.ldsp":     "",
	"c.sdsp":     "",
	"c.lq":       "",
	"c.sq":       "",
	"c.lqsp":     "",
	"c.sqsp":     "",
	"nop":        "",
	"mv":         "mv\t",
	"not":        "not\t",
	"neg":        "neg\t",
	"negw":       "NEGI32",
	"sext.w":     "SignEXtend.I32",
	"seqz":       "SetEqualZero",
	"snez":       "SetNotEqualZero",
	"sltz":       "SetLessThanZero",
	"sgtz":       "SetGreaterThanZero",
	"fmv.s":      "FloatMoVe.Single",
	"fabs.s":     "FloatABS.Single",
	"fneg.s":     "FloatNEGative.Single",
	"fmv.d":      "FloatMoVe.Double",
	"fabs.d":     "FloatABS.Double",
	"fneg.d":     "FloatNEGative.Double",
	"fmv.q":      "FloatMoVe.Quad",
	"fabs.q":     "FloatABS.Quad",
	"fneg.q":     "FloatNEGative.Quad",
	"beqz":       "BrEQualZero",
	"bnez":       "BrNotEqualZero",
	"blez":       "BrLessthanEqualZero",
	"bgez":       "BrGreaterEqualZero",
	"bltz":       "BrLessThanZero",
	"bgtz":       "BrGreaterThanZero",
	"ble":        "BrLessthanEqual",
	"bleu":       "BrLessthanEqualUnsigned",
	"bgt":        "BrGreaterThan",
	"bgtu":       "BrGreaterThanUnsigned",
	"j":          "Jump\t",
	"ret":        "",
	"jr":         "JumpReg",
	"rdcycle":    "ReadCYCLE",
	"rdtime":     "ReadTIME",
	"rdinstret":  "ReadINSTRET",
	"rdcycleh":   "ReadCYCLEHigh",
	"rdtimeh":    "ReadTIMEHigh",
	"rdinstreth": "ReadINSTRETHigh",
	"frcsr":      "FloatReadCSR",
	"frrm":       "FloatReadRoundingMode",
	"frflags":    "FloatReadFLAGS",
	"fscsr":      "FloatStoreCSR",
	"fsrm":       "FloatStoreRoundingMode",
	"fsflags":    "FloatStoreFLAGS",
	"fsrmi":      "FloatStoreRoundingModeImm",
	"fsflagsi":   "FloatStoreFLAGSImm",
	"li":         "LoadImm",
}

func rewriteDisasm(file string, debug bool) {
	var instream io.Reader
	instream = os.Stdin
	if file != "-" {
		cmd := exec.Command("llvm-objdump", "-d", file)
		in, err := cmd.StdoutPipe()
		if err != nil {
			log.Fatal(err)
		}
		defer in.Close()
		if err := cmd.Start(); err != nil {
			log.Fatal(err)
		}
		instream = in
	}

	scanner := bufio.NewScanner(instream)
	scanner.Split(bufio.ScanLines)

	// Assume the lines have the following format
	// <address and hex dump>\t<opcode>\t<operand>...
	for scanner.Scan() {
		line := scanner.Text()
		if debug {
			fmt.Println(line)
		}
		groups := strings.Split(line, "\t")
		if len(groups) < 2 {
			fmt.Println(line)
			continue
		}
		t := opcodeMap[groups[1]]
		if len(t) > 0 {
			groups[1] = t
		}
		output := groups[0]
		for _, s := range groups[1:] {
			output += ("\t" + s)
		}
		fmt.Println(output)
	}
}

func main() {
	if len(os.Args) != 2 {
		log.Println("Usage:")
		log.Printf("\t%s objfile  (\"llvm-objdump -d objfile\" is called internally)\n", os.Args[0])
		log.Printf("\t%s - < objdump_output\n", os.Args[0])
		os.Exit(1)
	}
	debug := false
	rewriteDisasm(os.Args[1], debug)
}
